<?php

namespace UtExam\ProEvalBundle\Repository;

/**
 * AlumnosEnExamenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlumnosEnExamenRepository extends \Doctrine\ORM\EntityRepository
{
}
