<?php

namespace UtExam\ProEvalBundle\Repository;

/**
 * AudioPreguntaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AudioPreguntaRepository extends \Doctrine\ORM\EntityRepository
{
}
