<?php

namespace UtExam\ProEvalBundle\Repository;

/**
 * CalificacionesDeMateriasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalificacionesDeMateriasRepository extends \Doctrine\ORM\EntityRepository
{
}
