<?php

namespace UtExam\ProEvalBundle\Repository;

/**
 * CalificacionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalificacionesRepository extends \Doctrine\ORM\EntityRepository
{
}
