<?php

namespace UtExam\ProEvalBundle\Repository;

/**
 * ExamenAutoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExamenAutoRepository extends \Doctrine\ORM\EntityRepository
{
}
