<?php

namespace UtExam\ProEvalBundle\Repository;

/**
 * ImagenPreguntaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImagenPreguntaRepository extends \Doctrine\ORM\EntityRepository
{
}
