<?php

namespace UtExam\ProEvalBundle\Repository;

/**
 * MaestrosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaestrosRepository extends \Doctrine\ORM\EntityRepository
{
}
