<?php

namespace UtExam\ProEvalBundle\Repository;

/**
 * preguntasinExamenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class preguntasinExamenRepository extends \Doctrine\ORM\EntityRepository
{
}
