<?php

namespace UtExam\ProEvalBundle\Repository;

/**
 * PreguntasAutoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PreguntasAutoRepository extends \Doctrine\ORM\EntityRepository
{
}
