<?php

namespace UtExam\ProEvalBundle\Repository;

/**
 * VideoPreguntaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoPreguntaRepository extends \Doctrine\ORM\EntityRepository
{
}
