imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@UtExamProEvalBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    templating:
        engines: ['twig']
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        entity_managers:
            default:
                auto_mapping: true
                mappings:
                    UtExamProEvalBundle: ~
                    SonataUserBundle: ~
                    FOSUserBundle: ~
                    ApplicationSonataUserBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

sensio_framework_extra:
   router:
        annotations: false

sonata_block:
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]

sonata_admin:
    title: Sipre Admin
    title_logo: "bundles/utexamproeval/images/utLogo.png"
    dashboard:
        groups:
            preguntas:
              label: 'Agregar Preguntas'
              label_catalogue: ~
              icon: '<i class="fa fa-pencil "></i>'
              items:
                  # - admin.imagen
                  # - admin.audio
                  # - admin.video
                  # - admin.imagenPregunta
                  # - admin.videoPregunta
                  # - admin.audioPregunta
                  # - admin.materias
                  - admin.Pregunta
                  # - admin.PreguntasAuto
                  # - admin.texto
                  # - admin.tipoPregunta
                  # - admin.respuestas
                  # - admin.preguntasinExamen
            examen:
              label: 'Crear Examen'
              label_catalogue: ~
              icon: '<i class="fa fa-archive "></i>'
              items:
                  - admin.examen
                  - admin.examenAuto
            createExamWord:
              label: 'Archivo PDF'
              label_catalogue: ~
              icon: '<i class="fa fa-file-pdf-o "></i>'
              items:
                  - admin.createExamWord
            createReporte:
              label: 'Reportes'
              label_catalogue: ~
              icon: '<i class="fa fa-table"></i>'
              items:
                  - admin.createReporte
            alumnos:
              label: 'Alumnos'
              label_catalogue: ~
              icon: '<i class="fa fa-address-book "></i>'
              items:
                  - admin.alumnos
                  - admin.alumnosEnExamen
            maestros:
              label: 'Maestros'
              label_catalogue: ~
              icon: '<i class="fa fa-address-book "></i>'
              items:
                  - admin.maestros

sonata_user:
    security_acl: true
    manager_type: orm
    class:
        user: Application\Sonata\UserBundle\Entity\User
        group: Application\Sonata\UserBundle\Entity\Group

fos_user:
    db_driver:      orm # can be orm or odm
    firewall_name:  main
    user_class:     Application\Sonata\UserBundle\Entity\User


    group:
        group_class:   App\Application\Sonata\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager # If you're using doctrine orm (use sonata.user.mongodb.group_manager for mongodb)

    service:
        user_manager: sonata.user.orm.user_manager

    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
